name: todolist
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.0.0 
  cloud_firestore: ^4.0.0 
  firebase_auth: ^4.0.0
  web: ^0.4.0
  font_awesome_flutter: ^10.7.0

  
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

  
